# Code generated by iron_sql, DO NOT EDIT.

# fmt: off
# pyright: reportUnusedImport=false
# ruff: noqa

import datetime
import decimal
import ipaddress
import uuid
from collections.abc import AsyncIterator
from collections.abc import Sequence
from contextlib import asynccontextmanager
from contextvars import ContextVar
from dataclasses import dataclass
from enum import StrEnum
from typing import Literal
from typing import overload

import psycopg
import psycopg.rows
from psycopg.types import json as pgjson

from iron_sql import runtime

from myapp.config import DSN

import myapp.models

MYDB_POOL = runtime.ConnectionPool(
    DSN,
    name="mydb",
    application_name=None,
)

_mydb_connection = ContextVar[psycopg.AsyncConnection | None](
    "_mydb_connection",
    default=None,
)


@asynccontextmanager
async def mydb_connection() -> AsyncIterator[psycopg.AsyncConnection]:
    async with MYDB_POOL.connection_in_context(
        _mydb_connection
    ) as conn:
        yield conn


@asynccontextmanager
async def mydb_transaction() -> AsyncIterator[None]:
    async with mydb_connection() as conn, conn.transaction():
        yield


class MydbTaskPriority(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class MydbTaskStatus(StrEnum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    DONE = "done"
    CANCELLED = "cancelled"


@dataclass(kw_only=True)
@runtime.json_validated(metadata=myapp.models.TaskMetadata)
class MydbTask:
    id: uuid.UUID
    project_id: uuid.UUID
    assignee_id: uuid.UUID | None
    title: str
    status: MydbTaskStatus
    priority: MydbTaskPriority
    metadata: myapp.models.TaskMetadata | None
    due_date: datetime.date | None
    created_at: datetime.datetime


@dataclass(kw_only=True)
class MydbUser:
    id: uuid.UUID
    username: str
    email: str
    created_at: datetime.datetime


@dataclass(kw_only=True)
class TaskStatusCount:
    status: MydbTaskStatus
    task_count: int


class Query:
    pass


class Query_07cbb3e5226e35adbd17171f38ab7216(Query):
    @asynccontextmanager
    async def _execute(self, params) -> AsyncIterator[psycopg.AsyncRawCursor[uuid.UUID]]:
        stmt = 'SELECT id FROM tasks WHERE project_id = $1 AND title = $2'
        async with (
            mydb_connection() as conn,
            psycopg.AsyncRawCursor(conn, row_factory=runtime.typed_scalar_row(uuid.UUID, not_null=True)) as cur,
        ):
            await cur.execute(stmt, params)
            yield cur

    async def query_all_rows(self, *, project_id: uuid.UUID, title: str) -> list[uuid.UUID]:
        async with self._execute((project_id, title)) as cur:
            return await cur.fetchall()

    async def query_single_row(self, *, project_id: uuid.UUID, title: str) -> uuid.UUID:
        async with self._execute((project_id, title)) as cur:
            return runtime.get_one_row(await cur.fetchmany(2))

    async def query_optional_row(self, *, project_id: uuid.UUID, title: str) -> uuid.UUID | None:
        async with self._execute((project_id, title)) as cur:
            return runtime.get_one_row_or_none(await cur.fetchmany(2))


class Query_12e061f7aa94bf484295ab0018520059(Query):
    @asynccontextmanager
    async def _execute(self, params) -> AsyncIterator[psycopg.AsyncRawCursor[None]]:
        stmt = 'UPDATE tasks SET status = $1 WHERE id = $2'
        async with (
            mydb_connection() as conn,
            psycopg.AsyncRawCursor(conn, row_factory=psycopg.rows.scalar_row) as cur,
        ):
            await cur.execute(stmt, params)
            yield cur

    async def execute(self, *, status: MydbTaskStatus, task_id: uuid.UUID) -> None:
        async with self._execute((status, task_id)):
            pass


class Query_41cb2f3cea216a76ba87b6ddb70e6be5(Query):
    @asynccontextmanager
    async def _execute(self, params) -> AsyncIterator[psycopg.AsyncRawCursor[MydbUser]]:
        stmt = 'SELECT id, username, email, created_at FROM users WHERE id = $1'
        async with (
            mydb_connection() as conn,
            psycopg.AsyncRawCursor(conn, row_factory=psycopg.rows.class_row(MydbUser)) as cur,
        ):
            await cur.execute(stmt, params)
            yield cur

    async def query_all_rows(self, *, user_id: uuid.UUID) -> list[MydbUser]:
        async with self._execute((user_id,)) as cur:
            return await cur.fetchall()

    async def query_single_row(self, *, user_id: uuid.UUID) -> MydbUser:
        async with self._execute((user_id,)) as cur:
            return runtime.get_one_row(await cur.fetchmany(2))

    async def query_optional_row(self, *, user_id: uuid.UUID) -> MydbUser | None:
        async with self._execute((user_id,)) as cur:
            return runtime.get_one_row_or_none(await cur.fetchmany(2))


class Query_46242a02ffe365dc17851a034fdc1d30(Query):
    @asynccontextmanager
    async def _execute(self, params) -> AsyncIterator[psycopg.AsyncRawCursor[MydbUser]]:
        stmt = 'SELECT id, username, email, created_at FROM users ORDER BY created_at'
        async with (
            mydb_connection() as conn,
            psycopg.AsyncRawCursor(conn, row_factory=psycopg.rows.class_row(MydbUser)) as cur,
        ):
            await cur.execute(stmt, params)
            yield cur

    async def query_all_rows(self) -> list[MydbUser]:
        async with self._execute(None) as cur:
            return await cur.fetchall()

    async def query_single_row(self) -> MydbUser:
        async with self._execute(None) as cur:
            return runtime.get_one_row(await cur.fetchmany(2))

    async def query_optional_row(self) -> MydbUser | None:
        async with self._execute(None) as cur:
            return runtime.get_one_row_or_none(await cur.fetchmany(2))


class Query_4726b127b54ccecbe95840ebb93221c6_TaskStatusCount(Query):
    @asynccontextmanager
    async def _execute(self, params) -> AsyncIterator[psycopg.AsyncRawCursor[TaskStatusCount]]:
        stmt = 'SELECT status, count(*) AS task_count FROM tasks WHERE project_id = $1 GROUP BY status ORDER BY status'
        async with (
            mydb_connection() as conn,
            psycopg.AsyncRawCursor(conn, row_factory=psycopg.rows.class_row(TaskStatusCount)) as cur,
        ):
            await cur.execute(stmt, params)
            yield cur

    async def query_all_rows(self, *, project_id: uuid.UUID) -> list[TaskStatusCount]:
        async with self._execute((project_id,)) as cur:
            return await cur.fetchall()

    async def query_single_row(self, *, project_id: uuid.UUID) -> TaskStatusCount:
        async with self._execute((project_id,)) as cur:
            return runtime.get_one_row(await cur.fetchmany(2))

    async def query_optional_row(self, *, project_id: uuid.UUID) -> TaskStatusCount | None:
        async with self._execute((project_id,)) as cur:
            return runtime.get_one_row_or_none(await cur.fetchmany(2))


class Query_518fda848857eb991e98c204381f945c(Query):
    @asynccontextmanager
    async def _execute(self, params) -> AsyncIterator[psycopg.AsyncRawCursor[None]]:
        stmt = 'INSERT INTO projects (id, name, owner_id, settings) VALUES ($1, $2, $3, $4)'
        async with (
            mydb_connection() as conn,
            psycopg.AsyncRawCursor(conn, row_factory=psycopg.rows.scalar_row) as cur,
        ):
            await cur.execute(stmt, params)
            yield cur

    async def execute(self, *, id: uuid.UUID, name: str, owner_id: uuid.UUID, settings: myapp.models.ProjectSettings) -> None:
        async with self._execute((id, name, owner_id, runtime.serialize_json_param(myapp.models.ProjectSettings, settings, 'jsonb'))):
            pass


class Query_ca1f790ce3eec6413c9e63c5ae05e2a9(Query):
    @asynccontextmanager
    async def _execute(self, params) -> AsyncIterator[psycopg.AsyncRawCursor[MydbTask]]:
        stmt = 'SELECT id, project_id, assignee_id, title, status, priority, metadata, due_date, created_at FROM tasks WHERE project_id = $1 AND ($2::task_status IS NULL OR status = $2)'
        async with (
            mydb_connection() as conn,
            psycopg.AsyncRawCursor(conn, row_factory=psycopg.rows.class_row(MydbTask)) as cur,
        ):
            await cur.execute(stmt, params)
            yield cur

    async def query_all_rows(self, *, project_id: uuid.UUID, status: MydbTaskStatus | None) -> list[MydbTask]:
        async with self._execute((project_id, status)) as cur:
            return await cur.fetchall()

    async def query_single_row(self, *, project_id: uuid.UUID, status: MydbTaskStatus | None) -> MydbTask:
        async with self._execute((project_id, status)) as cur:
            return runtime.get_one_row(await cur.fetchmany(2))

    async def query_optional_row(self, *, project_id: uuid.UUID, status: MydbTaskStatus | None) -> MydbTask | None:
        async with self._execute((project_id, status)) as cur:
            return runtime.get_one_row_or_none(await cur.fetchmany(2))


class Query_d270bc28e5b8b7becb60684dd230cbb3(Query):
    @asynccontextmanager
    async def _execute(self, params) -> AsyncIterator[psycopg.AsyncRawCursor[None]]:
        stmt = 'INSERT INTO users (id, username, email) VALUES ($1, $2, $3)'
        async with (
            mydb_connection() as conn,
            psycopg.AsyncRawCursor(conn, row_factory=psycopg.rows.scalar_row) as cur,
        ):
            await cur.execute(stmt, params)
            yield cur

    async def execute(self, *, id: uuid.UUID, username: str, email: str) -> None:
        async with self._execute((id, username, email)):
            pass


class Query_fae15665a7afc2e5599ebf694ab4fb07(Query):
    @asynccontextmanager
    async def _execute(self, params) -> AsyncIterator[psycopg.AsyncRawCursor[None]]:
        stmt = 'INSERT INTO tasks (id, project_id, title, priority, assignee_id, metadata, due_date) VALUES ($1, $2, $3, $4, $5, $6, $7)'
        async with (
            mydb_connection() as conn,
            psycopg.AsyncRawCursor(conn, row_factory=psycopg.rows.scalar_row) as cur,
        ):
            await cur.execute(stmt, params)
            yield cur

    async def execute(self, *, id: uuid.UUID, project_id: uuid.UUID, title: str, priority: MydbTaskPriority, assignee_id: uuid.UUID | None, metadata: myapp.models.TaskMetadata | None, due_date: datetime.date | None) -> None:
        async with self._execute((id, project_id, title, priority, assignee_id, runtime.serialize_json_param(myapp.models.TaskMetadata, metadata, 'jsonb'), due_date)):
            pass


_QUERIES: dict[str, type[Query]] = {
    "SELECT id, project_id, assignee_id, title, status, priority, metadata, due_date, created_at FROM tasks WHERE project_id = @project_id AND (sqlc.narg('status')::task_status IS NULL OR status = @status?)": Query_ca1f790ce3eec6413c9e63c5ae05e2a9,
    'INSERT INTO projects (id, name, owner_id, settings) VALUES (@id, @name, @owner_id, @settings)': Query_518fda848857eb991e98c204381f945c,
    'INSERT INTO tasks (id, project_id, title, priority, assignee_id, metadata, due_date) VALUES (@id, @project_id, @title, @priority, @assignee_id?, @metadata?, @due_date?)': Query_fae15665a7afc2e5599ebf694ab4fb07,
    'INSERT INTO users (id, username, email) VALUES (@id, @username, @email)': Query_d270bc28e5b8b7becb60684dd230cbb3,
    'SELECT id FROM tasks WHERE project_id = @project_id AND title = @title': Query_07cbb3e5226e35adbd17171f38ab7216,
    'SELECT id, username, email, created_at FROM users ORDER BY created_at': Query_46242a02ffe365dc17851a034fdc1d30,
    'SELECT id, username, email, created_at FROM users WHERE id = @user_id': Query_41cb2f3cea216a76ba87b6ddb70e6be5,
    'SELECT status, count(*) AS task_count FROM tasks WHERE project_id = @project_id GROUP BY status ORDER BY status': Query_4726b127b54ccecbe95840ebb93221c6_TaskStatusCount,
    'UPDATE tasks SET status = @status WHERE id = @task_id': Query_12e061f7aa94bf484295ab0018520059
}


@overload
def mydb_sql(stmt: Literal["SELECT id, project_id, assignee_id, title, status, priority, metadata, due_date, created_at FROM tasks WHERE project_id = @project_id AND (sqlc.narg('status')::task_status IS NULL OR status = @status?)"]) -> Query_ca1f790ce3eec6413c9e63c5ae05e2a9: ...
@overload
def mydb_sql(stmt: Literal['INSERT INTO projects (id, name, owner_id, settings) VALUES (@id, @name, @owner_id, @settings)']) -> Query_518fda848857eb991e98c204381f945c: ...
@overload
def mydb_sql(stmt: Literal['INSERT INTO tasks (id, project_id, title, priority, assignee_id, metadata, due_date) VALUES (@id, @project_id, @title, @priority, @assignee_id?, @metadata?, @due_date?)']) -> Query_fae15665a7afc2e5599ebf694ab4fb07: ...
@overload
def mydb_sql(stmt: Literal['INSERT INTO users (id, username, email) VALUES (@id, @username, @email)']) -> Query_d270bc28e5b8b7becb60684dd230cbb3: ...
@overload
def mydb_sql(stmt: Literal['SELECT id FROM tasks WHERE project_id = @project_id AND title = @title']) -> Query_07cbb3e5226e35adbd17171f38ab7216: ...
@overload
def mydb_sql(stmt: Literal['SELECT id, username, email, created_at FROM users ORDER BY created_at']) -> Query_46242a02ffe365dc17851a034fdc1d30: ...
@overload
def mydb_sql(stmt: Literal['SELECT id, username, email, created_at FROM users WHERE id = @user_id']) -> Query_41cb2f3cea216a76ba87b6ddb70e6be5: ...
@overload
def mydb_sql(stmt: Literal['SELECT status, count(*) AS task_count FROM tasks WHERE project_id = @project_id GROUP BY status ORDER BY status'], row_type: Literal['TaskStatusCount']) -> Query_4726b127b54ccecbe95840ebb93221c6_TaskStatusCount: ...
@overload
def mydb_sql(stmt: Literal['UPDATE tasks SET status = @status WHERE id = @task_id']) -> Query_12e061f7aa94bf484295ab0018520059: ...
@overload
def mydb_sql(stmt: str) -> Query: ...


def mydb_sql(stmt: str, row_type: str | None = None) -> Query:
    if stmt in _QUERIES:
        return _QUERIES[stmt]()
    msg = f"Unknown statement: {stmt!r}"
    raise KeyError(msg)
